apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ms-example
  namespace: argocd
  finalizers:
    # The default behaviour is foreground cascading deletion
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valueFiles:
      - values.yaml
      - values/ms-example.yaml
    path: microservices
    repoURL: https://github.com/zealotnt/k8s-argocd-example.git
    targetRevision: HEAD
  syncPolicy:
    automated: {}  # This enables auto-sync
    syncOptions:
    - RespectIgnoreDifferences=true
  ignoreDifferences:
  - group: ""
    kind: Secret
    name: ms-example-github-secrets
    namespace: default
    jsonPointers:
    - /data
