apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-application-kind
  namespace: test
spec:
  project: default
  source:
    chart: nginx
    repoURL: registry-1.docker.io/bitnamicharts  # note: the oci:// syntax is not included.
    targetRevision: 15.9.0
  destination:
    server: https://kubernetes.default.svc
    namespace: test
  syncPolicy:
    automated:
      pruneOlderVersions: true
