apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-ubuntu-app
  namespace: test
spec:
  project: default
  source:
    repoURL: https://github.com/zealotnt/k8s-argocd-example.git
    targetRevision: HEAD
    path: my-app
  destination:
    server: https://kubernetes.default.svc
    namespace: test
  syncPolicy:
    automated:
      pruneOlderVersions: true
  template:
    metadata:
      name: my-ubuntu-app
    spec:
      containers:
      - name: my-ubuntu-app
        image: zealotnt/ubuntu:24.04
        command: ["sleep", "1"]
