apiVersion: batch/v1
kind: Job
metadata:
  name: post-delete-job
  namespace: test
  finalizers:
    # The default behaviour is foreground cascading deletion
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/hook: PostDelete
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  template:
    spec:
      containers:
      - name: post-delete-container
        image: curlimages/curl
        command: ["/bin/sh", "-c"]
        args: [
          "curl -X POST https://webhook.site/02e02b8d-a843-4a7f-b183-66f03b520363 \
          -H 'Content-Type: application/json' \
          -d '{\"event\": \"PostDelete\", \"status\": \"completed\"}'"
        ]
      restartPolicy: OnFailure
