apiVersion: batch/v1
kind: Job
metadata:
  name: pre-sync-job
  namespace: test
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
  finalizers:
    # The default behaviour is foreground cascading deletion
    - resources-finalizer.argocd.argoproj.io
spec:
  template:
    spec:
      containers:
      - name: pre-sync-container
        image: curlimages/curl
        command: ["/bin/sh", "-c"]
        args: [
          "curl -X POST https://webhook.site/02e02b8d-a843-4a7f-b183-66f03b520363 \
          -H 'Content-Type: application/json' \
          -d '{\"event\": \"PreSync\", \"status\": \"started\"}'"
        ]
      restartPolicy: OnFailure
