apiVersion: batch/v1
kind: Job
metadata:
  name: sync-fail-job
  namespace: test
  annotations:
    argocd.argoproj.io/hook: SyncFail
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
      - name: sync-fail-container
        image: busybox
        command: ["/bin/sh", "-c"]
        args: ["echo Sync failed; taking action; sleep 5"]
      restartPolicy: OnFailure
