apiVersion: batch/v1
kind: Job
metadata:
  name: sync-job
  namespace: test
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
      - name: sync-container
        image: busybox
        command: ["/bin/sh", "-c"]
        args: ["echo Running sync hook; sleep 5"]
      restartPolicy: OnFailure
