apiVersion: batch/v1
kind: Job
metadata:
  name: sync-job
  namespace: test
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  template:
    spec:
      containers:
      - name: sync-container
        image: curlimages/curl
        command: ["/bin/sh", "-c"]
        args: [
          "curl -X POST https://webhook.site/02e02b8d-a843-4a7f-b183-66f03b520363 \
          -H 'Content-Type: application/json' \
          -d '{\"event\": \"Sync\", \"status\": \"in progress\"}'"
        ]
      restartPolicy: OnFailure
