apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.appLabel }}-post-delete-job
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/hook: PostDelete
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  template:
    spec:
      containers:
      - name: post-delete-container
        image: curlimages/curl
        command: ["/bin/sh", "-c"]
        args: [
          "curl -X POST https://webhook.site.tamsmarthome.xyz/81750696-482f-4d67-99da-5e03ccd9739f \
          -H 'Content-Type: application/json' \
          -d '{\"event\": \"PostDelete\", \"status\": \"completed\", \"pod_name\": \"$(POD_NAME)\", \"pod_namespace\": \"$(POD_NAMESPACE)\", \"pod_ip\": \"$(POD_IP)\", \"node_name\": \"$(NODE_NAME)\"}'"
        ]
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
      restartPolicy: OnFailure
