apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Values.appLabel }}"-pre-sync-job
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  template:
    spec:
      containers:
      - name: pre-sync-container
        image: curlimages/curl
        command: ["/bin/sh", "-c"]
        args: [
          "curl -X POST https://webhook.site/02e02b8d-a843-4a7f-b183-66f03b520363 \
          -H 'Content-Type: application/json' \
          -d '{\"event\": \"PreSync\", \"status\": \"started\"}'"
        ]
      - name: pre-sync-container-info
        image: curlimages/curl
        command: ["/bin/sh", "-c"]
        args: [
          "curl -X POST https://webhook.site/02e02b8d-a843-4a7f-b183-66f03b520363 \
          -H 'Content-Type: application/json' \
          -d '{\"event\": \"PreSync\", \"pod_name\": \"$(POD_NAME)\", \"pod_namespace\": \"$(POD_NAMESPACE)\", \"pod_uid\": \"$(POD_UID)\", \"pod_ip\": \"$(POD_IP)\", \"pod_ips\": \"$(POD_IPS)\", \"node_ip\": \"$(NODE_IP)\", \"node_ips\": \"$(NODE_IPS)\", \"node_name\": \"$(NODE_NAME)\", \"service_account_name\": \"$(SERVICE_ACCOUNT_NAME)\"}'"
        ]
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_UID
          valueFrom:
            fieldRef:
              fieldPath: metadata.uid
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: POD_IPS
          valueFrom:
            fieldRef:
              fieldPath: status.podIPs
        - name: NODE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: NODE_IPS
          valueFrom:
            fieldRef:
              fieldPath: status.hostIPs
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: SERVICE_ACCOUNT_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.serviceAccountName
      restartPolicy: OnFailure