apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.appLabel }}-github-secrets"
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  {{- range $key, $value := .Values.secrets }}
  {{ $key }}: {{ $value }}
  {{- end }}