appCommand: sleep
appArgs: 1
appLabel: applabel-example
repoLabel: repolabel-example
namespace: default
replicasCount: 1
image: zealotnt/ubuntu:24.04
resources:
  limits:
    cpu: "250m"
    memory: "256Mi"
  requests:
    cpu: "250m"
    memory: "256Mi"
containerhttpPort: 80
containerhttpsPort: 443